image: Visual Studio 2019
version: '2.1.0-build{build}'
init:
  - if %APPVEYOR_REPO_TAG%==true (appveyor UpdateBuild -Version "%APPVEYOR_BUILD_VERSION%")
skip_branch_with_pr: true
skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.props'
  version: '{version}'
  package_version: '{version}'
configuration: Release
before_build:
  - appveyor-retry dotnet restore -v Minimal
build:
  parallel: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal
deploy:
  - provider: NuGet
    api_key:
      secure: 7yj4aK5rp2V1xKRQ/p3tiF+Xu0YEXOkKRAxyDjbf52rOlQ1vVXK0P/LvIp4MmYrK
    on:
      branch: develop
  - provider: NuGet
    api_key:
      secure: 7yj4aK5rp2V1xKRQ/p3tiF+Xu0YEXOkKRAxyDjbf52rOlQ1vVXK0P/LvIp4MmYrK
    on:
      appveyor_repo_tag: true
  - provider: GitHub
    description: AppVeyor CI deployment
    auth_token:
      secure: IApJWoucWEA6qjZn1atyOtaEMbBJVMcs8r4AeTwX3yOPWYK76w6VzOpzG+eTainp
    draft: false
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: true